### ISSUE TITLE
Will multiv2 be apache licensed?

### ISSUE THREAD

**Issue by AIMads** [urchade/GLiNER#11]

**Comment by urchade** [comment]
Yup, 
But v2 results are lower, as the training dataset NuNER have short input size compared to Pile-NER (which NC license).

**Comment by AIMads** [comment]
Okay interesting, are you expecting it to be the best commercial licensed multi lingual NER model? Great work 💪

**Comment by urchade** [comment]
Thank you 😊 . "are you expecting it to be the best commercial licensed multi lingual NER model ?" That's the plan, but there are still many research questions (see Readme). The bottleneck for now is the multilingual data availability.

**Comment by brianjking** [comment]
I'm confused, are these models available for commercial usage or not? The LICENSE file is Apache 2, but then the models on Huggingface all show CC-BY-NC.

@urchade

**Comment by urchade** [comment]
Hi, only model trained on Pile-NER are CC-BY-NC. However models trained on NuNer (all v2's) are Apache 2.0. @brianjking 

Be aware v2 have slighly worse result, but <e are currently working on trained stronger permissible models.

**Comment by urchade** [comment]
@AIMads @brianjking Multilingual v2.1 is available: https://huggingface.co/urchade/gliner_multiv2.1
