### ISSUE TITLE
Organize dataset for training

### ISSUE THREAD

**Issue by AleKitsune98** [urchade/GLiNER#110]
How to organize training dataset for train.py script?

**Comment by urchade** [comment]
hi, you can look at https://github.com/urchade/GLiNER/tree/main/data for da processing

**Comment by AleKitsune98** [comment]
Can you share an example of training using a BERT model as base model and using correct data processing?

**Comment by urchade** [comment]
Have you fixed the issue ? I have been at some seminar last week, so did not have time to respond
