### ISSUE TITLE
Train with examples with and without entities

### ISSUE THREAD

**Issue by rmitsch** [urchade/GLiNER#111]
Currently trying to train with examples with and without entities. So my training dataset looks like this:
```
{'ner': [(4, 5, 'PER'),], 'tokenized_text': [...]}
{'ner': [], 'tokenized_text': [...]}
...
```
Training with this dataset produces `RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous` in `model.SpanGLiNER.forward()` in this line:
```
# loss for filtering classifier
logits_label = scores.view(-1, num_classes)
```

Training without labels is important though, as I need the model to recognize when _not_ to identify spans too. What's the canonical way to train with examples without entities?

Thanks for the help!

**Comment by urchade** [comment]
Hi @rmitsch, gliner needs at least entity names. you can set it like this: `{'ner': [], 'tokenized_text': [...], 'label':['person', 'location', ...]}`

**Comment by rmitsch** [comment]
Works. Thank you!
