### ISSUE TITLE
GliNER marking pronouns as PERSON

### ISSUE THREAD

**Issue by manojkumarvohra** [urchade/GLiNER#115]
GliNER is tagging pronouns like I, you, we, they as PERSON entity type.

These are not named entities and should not be picked by the model.

Only named entities (person names/nouns) should be picked.

<img width="781" alt="Screenshot 2024-06-12 at 10 07 15 AM" src="https://github.com/urchade/GLiNER/assets/17252390/5284f472-c366-4cf6-8974-64bc130403a8">
<img width="768" alt="Screenshot 2024-06-12 at 10 07 05 AM" src="https://github.com/urchade/GLiNER/assets/17252390/c83d3348-03ea-4f85-9ebd-98cb49ddf06c">
<img width="785" alt="Screenshot 2024-06-12 at 10 06 42 AM" src="https://github.com/urchade/GLiNER/assets/17252390/441b191c-22a7-4706-9988-69bafd2a0c93">
<img width="762" alt="Screenshot 2024-06-12 at 10 06 31 AM" src="https://github.com/urchade/GLiNER/assets/17252390/33f26364-14b1-4e9e-9d7a-a61725339275">
<img width="792" alt="Screenshot 2024-06-12 at 10 06 21 AM" src="https://github.com/urchade/GLiNER/assets/17252390/44a8e3de-2a4c-4b02-98a8-059212057746">

**Comment by urchade** [comment]
Unfortunately, this was the case in the training dataset . Try to change the label name

**Comment by manojkumarvohra** [comment]
when you say changing label name ... can you please elaborate on it?

**Comment by manojkumarvohra** [comment]
Unfortunately its not working with a changed label.

![Screenshot 2024-06-13 at 3 11 03 PM](https://github.com/urchade/GLiNER/assets/17252390/bbee1ff8-a76d-4453-960c-2be1f6ae7afd)

However increasing the threshold does seems to ignore pronouns but that would mean trading off the detection rate?

![Screenshot 2024-06-13 at 3 11 35 PM](https://github.com/urchade/GLiNER/assets/17252390/8f4e73f9-a69a-427c-b0f9-8800b1f23e27)

**Comment by urchade** [comment]
there are infinite possible label name, try to find the one that works

or change the model you use. Which model version is this ?

**Comment by manojkumarvohra** [comment]
I am using gliner_multi_pii-v1 through a spacy pipe integrated with Presidio.

I see presidio follows its own entity labels.

**Comment by urchade** [comment]
if you are interested with pii, you can check this blogpost: https://ai.gopubby.com/zero-shot-named-entity-recognition-ner-c81f82cb0f70

**Comment by robcaulk** [comment]
Hey @manojkumarvohra , did gliner_medium_news end up helping you?

**Comment by manojkumarvohra** [comment]
Hi @robcaulk , Unfortunately no. gliner_medium_news also showed same detections with pronouns.

I had to do post processing to handle pronouns.

**Comment by robcaulk** [comment]
@manojkumarvohra and you are not using English right? That’s almost definitely the cause. GLiNER medium news is fine tuned for English translated sources, not the original text itself.

**Comment by manojkumarvohra** [comment]
Hi @robcaulk, our text is primarily in English. However I was also evaluating multi lingual support with Gliner.
Our post processing handling for pronouns is from English only.
