### ISSUE TITLE
When will relation extraction be extended to GLINER

### ISSUE THREAD

**Issue by parthplc** [urchade/GLiNER#118]
Hey Guys, Amazing work. Wanted to know if there is any timeline for relation extraction with GLINER. I have checked your colab in GRAPHER. Any update on how we can use Glinerr with it? Thank you

**Comment by Ingvarstep** [comment]
Hey @parthplc , you can check my recent work, this is still a research project, but it's already promising. [Here](https://huggingface.co/knowledgator/gliner-multitask-large-v0.5#construct-relations-extraction-pipeline-with-utca) you will find how to use this multi-task GLiNER model for relation extraction.

**Comment by jackboyla** [comment]
hey @parthplc, I've been working on a relation extraction extension of gliner. It's still in development but you can check it out here https://github.com/jackboyla/GLiREL

**Comment by parthplc** [comment]
Hey @jackboyla , Thanks! Looks promising. Will check it out.

**Comment by urchade** [comment]
Nice work @jackboyla 🔥
