### ISSUE TITLE
Error: dictionary is accessed with index

### ISSUE THREAD

**Issue by ajay-sreeram** [urchade/GLiNER#122]
https://github.com/urchade/GLiNER/blob/99130ad5fab7ddd63fbcf799d5c422e490394f00/gliner/data_processing/processor.py#L243

In the above code,  batch['classes_to_id'] is a dictionary but is accessed like a list. I think it should be corrected to `classes_to_id = batch['classes_to_id']`

**Comment by ajay-sreeram** [comment]
hi @Ingvarstep yes when i set get_negatives to false, i get the index error.

**Comment by ajay-sreeram** [comment]
and also one more thing is mention, when calling predict_entities with very small threshold like 0.01, it throws key error at line:

https://github.com/urchade/GLiNER/blob/99130ad5fab7ddd63fbcf799d5c422e490394f00/gliner/decoding/decoder.py#L50

**Comment by Ingvarstep** [comment]
> hi @Ingvarstep yes when i set get_negatives to false, i get the index error.

@ajay-sreeram , I got it, the issue was fixed in the last commit. Currently, GLiNERDataset is used only for training with the Transformers library, I have fixed the negative sampling process and right now it should work properly.

**Comment by ajay-sreeram** [comment]
Thank you @Ingvarstep
