### ISSUE TITLE
all entities must be a sequence

### ISSUE THREAD

**Issue by ChenghaoMou** [urchade/GLiNER#127]
```
negatives = random.sample(self.all_entities, k=self.max_negatives)
```
will raise an issue:
```
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

if self.all_entities are collected from the function `self._collect_all_entities()` which returns a dict instead of list.

**Comment by Ingvarstep** [comment]
@ChenghaoMou , thank you for pointing out this issue. This issue emerges for Python versions higher than 3.11.0

Changed in version 3.11: The population must be a sequence. Automatic conversion of sets to lists is no longer supported.
https://docs.python.org/3/library/random.html#random.sample
