### ISSUE TITLE
Supported entity types

### ISSUE THREAD

**Issue by lucazav** [urchade/GLiNER#131]
Is there a comprehensive list of entity types supported by GLiNER? For example, I found that "Acronym" and "Abbreviation" are supported. I can't find all of them in the documentation.

Thank you.

**Comment by urchade** [comment]
Hi @lucazav 
GLiNER is intended to support any entity types, at it uses entity string representation

**Comment by lucazav** [comment]
@urchade Thanks for your feedback. Anyway, I'm wondering if there's a complete list of entity types used in the standard training. I'm asking because I stumbled across the "Abbreviation" one by accident. If I had a complete list, I would see all the allowed types by default with a quick view.

**Comment by urchade** [comment]
Hi @lucazav, maybe you can directly check the training data here: https://huggingface.co/datasets/Universal-NER/Pile-NER-type?row=3
