### ISSUE TITLE
NumPy issue with 0.25 GLiNER

### ISSUE THREAD

**Issue by davidress-ILW** [urchade/GLiNER#134]
I just created a clean environment based on python 3.10 in PyCharm, added the gliner librarr (0.25) and the program crashes on line 1:

`from gliner import GLiNER`

With the following error:

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Python\GLiNERdemo\gliner_demo.py", line 1, in <module>
    from gliner import GLiNER
  File "C:\venv_2024\GLiNERdemo\lib\site-packages\gliner\__init__.py", line 3, in <module>
    from .model import GLiNER
  File "C:\venv_2024\GLiNERdemo\lib\site-packages\gliner\model.py", line 15, in <module>
    from .onnx.model import BaseORTModel, SpanORTModel, TokenORTModel
  File "C:\venv_2024\GLiNERdemo\lib\site-packages\gliner\onnx\model.py", line 4, in <module>
    import onnxruntime as ort
  File "C:\venv_2024\GLiNERdemo\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\venv_2024\GLiNERdemo\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found

The code worked fine with 0.24 but 0.25, which was just released, has issues for me. Any advice?

Of course this happens the evening before I am to demonstrate this software to my company, ;).

Thanks,
David

**Comment by htqxjj** [comment]
pip uninstall numpy
pip install numpy==1.26.4

**Comment by Ingvarstep** [comment]
@davidress-ILW, I am sorry that you experienced it. Yes, the easiest way is to downgrade Numpy as in the comment above. Also, one question, are you sure that Numpy is not pre-installed for some reason in your environment?

**Comment by davidress-ILW** [comment]
Sorry for my late reply, but thank you for the help.  I think it was Jupyter notebook or something else that got pulled into my environment by IT that pushed numpy to 2.0. Downgrading it to 1.26.4 worked.

Thanks again, this software is awesome.
