### ISSUE TITLE
Dataset generate 

### ISSUE THREAD

**Issue by drewskidang** [urchade/GLiNER#17]
Sorry do you know how to create the dataset custom. Can’t figure out the template to get similar format

**Comment by urchade** [comment]
I am not sure to understand your question. You can look inside data/ for preprocessing of training datasets.  Also in example/ there is a sample dataset.

Tell me if this answer your question

**Comment by drewskidang** [comment]
Sorry i was wondering if there was a way to have an LLM create a custom dataset synthetically. Wanted the model to be tailored a specific domain

**Comment by urchade** [comment]
You can use the method from UniversalNER (https://arxiv.org/pdf/2308.03279.pdf)
<img width="366" alt="image" src="https://github.com/urchade/GLiNER/assets/38214774/9a17cae7-535c-40e6-aefb-6e6dd2c9b7fb">

**Comment by drewskidang** [comment]
oh thank you
