### ISSUE TITLE
Request to Add GLiNER to Conda-Forge

### ISSUE THREAD

**Issue by sdhdez** [urchade/GLiNER#179]
Hi Urchade,

First of all, thank you for developing and maintaining the **GLiNER** package. It has been incredibly useful for our projects, and I’m sure many others feel the same way.

I am writing to request that you consider adding GLiNER to the **conda-forge** repository. Here are a few reasons why this would be beneficial:

- **Ease of Installation**: Conda is a widely used package manager, especially in the scientific and data science communities. Having GLiNER available on conda-forge would simplify the installation process for many users, eliminating the need for manual dependency management.
- **Wider Reach**: By adding GLiNER to conda-forge, you can reach a broader audience. Many users prefer or are required to use conda environments, and having GLiNER readily available would make it more accessible to them.
- **Consistency and Compatibility**: Conda-forge ensures that packages are built in a consistent environment, which can help avoid compatibility issues. This would make it easier for users to integrate GLiNER into their existing workflows without encountering unexpected problems.
- **Community Support**: Being part of conda-forge means that the package can benefit from the community’s support in terms of maintenance and updates. This can help ensure that GLiNER remains up-to-date with the latest dependencies and best practices.

I believe that adding GLiNER to conda-forge would greatly enhance its usability and adoption. If you need any assistance with the process, I would be more than happy to help.

Thank you for considering this request.

Best regards,

Simon

**Comment by urchade** [comment]
Hi @sdhdez, Thank you for your interest in GLiNER !

I think that @moritzwilksch has been working on this. You can check this repo: https://github.com/conda-forge/gliner-feedstock

**Comment by sdhdez** [comment]
Thank you for the info!
