### ISSUE TITLE
model max length 

### ISSUE THREAD

**Issue by abpani** [urchade/GLiNER#185]
I verified with microsoft/mdeberta-v3-base tokenization. The max length with the tokenization and this finetuned model is really different.
ids = tokenizer(text, add_special_tokens=False, max_length=256, stride=10, return_overflowing_tokens=True, truncation=True, padding=False)
len(ids.input_ids[0]) : 256
text = tokenizer.decode(ids.input_ids[0])
model.predict_entities(text, labels=labels, threshold=0.5)
gliner/data_processing/processor.py:206: UserWarning: Sentence of length 422 has been truncated to 384

Please help how can I ensure splitting so that there is no truncation

**Comment by gskrypka** [comment]
Hi. I'm wondering was the problem solved?

**Comment by abpani** [comment]
> Hi. I'm wondering was the problem solved?

yes 
https://huggingface.co/E3-JSI/gliner-multi-pii-domains-v1/discussions/1
