### ISSUE TITLE
Add support for loading models via safetensors

### ISSUE THREAD

**Issue by vrdn-23** [urchade/GLiNER#186]
Thanks a lot for the awesome project!
Loading models through .bin executables are inherently risky and can lead to malicious code execution. Please consider adding support for loading the [safetensors variant](https://github.com/huggingface/safetensors) of the models provided.

If this is something that you would be interested in, I'd be happy to help out with a PR!

**Comment by xingchaozh** [comment]
looking forward to

**Comment by vrdn-23** [comment]
@urchade I've raised a PR to fix the issue. Let me know if you have any comments!

**Comment by urchade** [comment]
Thank you @vrdn-23, will review it soon!

**Comment by vrdn-23** [comment]
@urchade Thanks for reviewing! Is there an ETA on when the next release is going to be cut?
