### ISSUE TITLE
Batched prediction fails

### ISSUE THREAD

**Issue by tomaarsen** [urchade/GLiNER#19]
Hello!

## Bug details
When I run `batch_predict_entities` I get an unexpected IndexError.

## How to reproduce
```python
from gliner import GLiNER

model = GLiNER.from_pretrained("urchade/gliner_base")

texts = ["This is one text with Urchade Zaratiana as a name way later on", "And this is another one"]
output = model.batch_predict_entities(texts, labels=['date', 'location', 'person', 'organization', 'airplane'])
print(output)
```

## Cause
It's caused by these variables, which will only stay for the last text:
https://github.com/urchade/GLiNER/blob/main/gliner/model.py#L303-L304

We need to keep track of these, one per input text, just like the `all_tokens`.

I'll prep a PR.

- Tom Aarsen

**Comment by urchade** [comment]
I see, my test was not robust enough, thanks for catching
