### ISSUE TITLE
Entity types in Pile-NER

### ISSUE THREAD

**Issue by MikeNLP** [urchade/GLiNER#21]
Thank you for sharing your preprocessing scripts. I download the dataset from [https://huggingface.co/datasets/Universal-NER/Pile-NER-type](url) and preprocess it with your script. Then I count the number of entity types with the following script:
`import json

with open("../dataset/pilener_train.json", 'r') as f:
    data = json.load(f)

entity_set = list()
for d in data:
    for ner in d['ner']:
        entity_set.append(ner[-1].lower())
entity_list = list(set(entity_set))
print(len(entity_list))`

However, the result is **12620**, which is inconsistent with the result 13020 in the original paper (also inconsistent with the result of 13k in your paper). If I remove 'lower()' in 'entity_set.append(ner[-1].lower())' in my script, I get the result **15176**.

I'm wondering if there's anything I've overlooked. Could you please provide me with some advice?

**Comment by urchade** [comment]
No worry, in the paper, I approximate the results and the number 12,620 is rounded to 13k. That's why. @MikeNLP

**Comment by MikeNLP** [comment]
Thank you for your kind reply.
