### ISSUE TITLE
Self defined entities

### ISSUE THREAD

**Issue by skwskwskwskw** [urchade/GLiNER#23]
Hi, 

Can the model be used to train on own dataset with self-defined entity types? If so, is there a tutorial how to do it? 

Thanks.

**Comment by urchade** [comment]
You can look at examples/ there is fine-tuning notebook. You may also check train.py and data/

**Comment by urchade** [comment]
yes, exactly

**Comment by urchade** [comment]
You should pass a validation data (eval_data) to monitor the performance

you can also modify the code and log the validation performance in a text file
