### ISSUE TITLE
Encountering an error during fine-tuning with a custom NER dataset on GPU.

### ISSUE THREAD

**Issue by ganga7445** [urchade/GLiNER#25]
@tomaarsen @urchade 
RuntimeError: cudnn RNN backward can only be called in training mode

![Screenshot from 2024-03-18 17-50-21](https://github.com/urchade/GLiNER/assets/13760286/2f64d43d-1d6b-4825-b081-9a4461324581)

**Comment by urchade** [comment]
Call model.train() to make in training mode

**Comment by ganga7445** [comment]
@urchade i  have used model.eval() before evaluating.still getting same error. can you make the changes and push to [finetune.ipynb](https://github.com/urchade/GLiNER/blob/main/examples/finetune.ipynb)

**Comment by urchade** [comment]
I will do it later

For now you can add, ```model.train()``` after ```model.save_pretrained```

**Comment by ganga7445** [comment]
cool.working fine @urchade thanks
