### ISSUE TITLE
Accuracies at entity level on train/dev/test data

### ISSUE THREAD

**Issue by ganga7445** [urchade/GLiNER#30]
I'm currently fine-tuning a custom Named Entity Recognition (NER) dataset on a GPU.
 I've managed to attain accuracies for each set. 
How can we further obtain accuracies at the entity level?
@urchade @tomaarsen can you help me here?

**Comment by urchade** [comment]
I haven't implemented it

Does fine-tuning work well? I haven't really test the notebook on real scenario

**Comment by urchade** [comment]
What you can do is transform the result into bio sequence and use library such as seqeval

**Comment by ganga7445** [comment]
yup. fine tuning is working fine now. I can convert it to a BIO sequence and proceed with evaluation using seqeval.
