### ISSUE TITLE
Changing the base DeBERTa model. PT benchmark.

### ISSUE THREAD

**Issue by marquesafonso** [urchade/GLiNER#31]
First of all, thank you for this work!

I was wondering whether it would be possible to change the base encoder model to a language specific model, namely a finetuned version of DeBERTa model.

From analyzing the code in model.py it would seem like a one-off solution where you simply switch the base DeBERTa model is not possible, it only allows choosing microsoft/deberta-v3-base or microsoft/mdeberta-v3-base.

Given this, am I right to assume I would need to retrain the model changing the model_name parameter in the configs to the desired model namespace in huggingface? In that case, would you advise to train with all of the Pile-NER dataset or trying to select only the portuguese bits?

Sorry for the long questionnaire... Since I would not want to be all *take* and *no give*, I have conducted a small comparison on a portuguese NER benchmark [HAREM 2](https://github.com/marquesafonso/harem_preprocessing) dataset for 5 categories (PER, LOC, TEMP, VAL, ORG) and with a conservative threshold of 0.85 it is not far from the best ner model I am aware of [bertimbau-large-ner-selective](https://huggingface.co/marquesafonso/bertimbau-large-ner-selective).

<table>
  <thead>
    <tr>
      <th>Metrics</th>
      <th>bertimbau-ner-selective</th>
      <th>gliner_multi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Precision</td>
      <td>0.65</td>
      <td>0.70</td>
    </tr>
    <tr>
      <td>Recall</td>
      <td>0.63</td>
      <td>0.56</td>
    </tr>
    <tr>
      <td>F1-score</td>
      <td>0.64</td>
      <td>0.62</td>
    </tr>
  </tbody>
</table>

**Comment by urchade** [comment]
Hi, thank you for the evaluation.

Actually, you can use GLiNER with any transformer/BERT model from Hugging Face. You can set it in the [config file](https://github.com/urchade/GLiNER/blob/main/config_large.yaml) when training a model. Also, you can construct the Pile-NER dataset using the script in [data](https://github.com/urchade/GLiNER/tree/main/data).

I recently released a new dataset, [Pile-Mistral-v01](https://huggingface.co/datasets/urchade/pile-mistral-v0.1/blob/main/data.json), available on Hugging Face, which contains already preprocessed data.

**Comment by marquesafonso** [comment]
Great. That was my understanding, thank for your quick reply. I'll give it a try and see.

**Comment by marquesafonso** [comment]
Hello again! I have been trying to train a model from scratch, changing the base model to deberta variant, as per our previous conversation. I have tried both on my cpu and on collab and in both cases the RAM has been exhausted causing the training to be early terminated (in step 0 or 1).
Could you please share on what specs you trained the model? Did you face similar issues and have any advice?

**Comment by urchade** [comment]
@marquesafonso It should be easier to train using the NuNer dataset as the text lengths are shorter.

I think training on CPU would be a bit complicated. I have trained the model on a A100 GPU.

**Comment by marquesafonso** [comment]
Thanks for the reply.

The problem also existed for GPU in the free tier if colab and in an A100 - essentially CUDA out of memory. It pointed me [here](https://pytorch.org/docs/stable/notes/cuda.html#environment-variables).

`OutOfMemoryError: CUDA out of memory. Tried to allocate 432.00 MiB. GPU 0 has a total capacity of 39.56 GiB of which 82.81 MiB is free. Process 39550 has 39.47 GiB memory in use. Of the allocated memory 34.93 GiB is allocated by PyTorch, and 4.02 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management `

Solved by changing to A100 AND setting the following environment variables
!set PYTORCH_NO_CUDA_MEMORY_CACHING=1
!set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
