### ISSUE TITLE
ONNX support for inference

### ISSUE THREAD

**Issue by ganga7445** [urchade/GLiNER#34]
@urchade Is there a plan for an ONNX exporter? Have you experimented with using GLiNER with ONNX models for inference? I'm quite curious if you've explored that avenue already! :-)

**Comment by urchade** [comment]
I am not familiar with ONNX, unfortunately

Do you have any idea how that can be done ?

**Comment by xenova** [comment]
Amazing! 🥳 I've made conversions (+quantizations) for a bunch of GLiNER models and uploaded them to the Hugging Face Hub: https://huggingface.co/models?library=gliner,onnx&sort=trending. Feel free to link to these in the README, if you'd like 😇

**Comment by urchade** [comment]
Great! Thank you @xenova
