### ISSUE TITLE
train.py does not achieve the desired results

### ISSUE THREAD

**Issue by Serega6678** [urchade/GLiNER#36]
Hey guys, thank you for your great work! Was genuinely surprised with your Zero-Shot results compared to bigger LLMs.

I tried to reproduce the results of GLiNER large by pre-processing the entire Pile dataset by UniversalNER using ```data_proc.py```
Then I trained using ```python train.py --config config_large.yaml``` And the zero-shot results I got were 5% below the reported ones in the paper (I attach the file).

In short, the performance on Zero-Shot CrossNER degraded from the expected 60% to around 55%: [tables.txt](https://github.com/urchade/GLiNER/files/14693361/tables.txt)

For evaluation, I am using the ```get_for_all_path``` function and I evaluate within the ```train.py``` while training (basically I use your train.py to train and evaluate the model)

What am I missing?
Many thanks

**Comment by urchade** [comment]
Hi @Serega6678, thank you for your interest in GLiNER.

There could be many reasons for that:
- The results reported in the paper were using AllenNLP for some modules including the LSTM and the span representation. As AllenNLP is no longer maintained, this causes some dependency problems, so I had to reimplement some modules in pure pytorch to facilitate usability.
- I recently reimplemented the original span representation module under "markerV0" for span representation. It should increase the score.
- The hardware setup may also influence the training dynamics. Also try to tune a bit the hyperparameters.

**Comment by Serega6678** [comment]
Makes sense, thank you

Would it be possible to privately share the initial model code with AllenNLP? I don't care about the code quality, etc, I just want to fix the final score of the model

**Comment by urchade** [comment]
[Archive.zip](https://github.com/urchade/GLiNER/files/14694798/Archive.zip)

Here is the code I used during experimentation. (indeed it's a bit messy)

**Comment by Serega6678** [comment]
Appreciate it a lot
