### ISSUE TITLE
How run GLiNER from Local Disc after Git clone on Local

### ISSUE THREAD

**Issue by aliraja** [urchade/GLiNER#41]
Hi, I have cloned the repo of the GLiNER using the sudo git clone https://huggingface.co/urchade/gliner_base

also have installed the sudo -H pip3 install --upgrade gliner

Now I want to load the model from the local path like in piplines transformers, 

currently it loads using the `from gliner import GLiNER

model = GLiNER.from_pretrained("urchade/gliner_base")`

But I want it to load like `from gliner import GLiNER
model = GLiNER.from_pretrained('/home/A/Modal/gliner_base', local_files_only=True)` 

please advice

**Comment by tomaarsen** [comment]
Hello!

I think you might be experiencing the same issue as #35. I hope that #42 should fix that bug. In the meantime, perhaps you can make the edit from #42 to your own git clone to see if that helps.

- Tom Aarsen

**Comment by urchade** [comment]
https://github.com/urchade/GLiNER/blob/main/examples/load_local_model.ipynb
