### ISSUE TITLE
GLiNER-small and GLiNER-large

### ISSUE THREAD

**Issue by tomaarsen** [urchade/GLiNER#5]
Hello!

Will you be releasing your checkpoints for GLiNER-small and GLiNER-large also? I think they would be valuable for the community.
I will be sharing your work on socials today - perhaps some of the many users of [UniNER-7B-all](https://huggingface.co/Universal-NER/UniNER-7B-all) will be motivated to experiment with GLiNER instead.

- Tom Aarsen

**Comment by urchade** [comment]
Hi, sure I will work on it if it can be useful to people, as well as the small version. Previous version of GLiNER used allennlp (which is no longer maintained), which caused some conflicts and environmental issues. 

The checkpoints I have are not compatible and I have to retrain the models.

**Comment by tomaarsen** [comment]
Makes sense. It's up to you whether you want to do that or not :) 
I've created a demo on Hugging Face showcasing the base model & I'll share it later today. Hopefully it'll catch people's interest.

- Tom Aarsen

**Comment by urchade** [comment]
Wow, the demo is awesome and the model seems to work well. Thanks so much for your assistance. I tried to capture people before, but didn't get much visibility, although the few people who have tried the model were satisfied (like the one from reddit in the screenshot).
![image_2024-03-08_105841585](https://github.com/urchade/GLiNER/assets/38214774/c0485799-e562-4dfc-a397-f1fed471d346)

**Comment by galprz-renovai** [comment]
Hey @tomaarsen thanks for sharing this model and more important thank you @urchade for the contribution. i want to try to train GLiNER for a domain specific. can you please share the format of the dataset that train.py need to get?

**Comment by urchade** [comment]
Hi, the format is a json file list of samples:

```json
[
        {
            "tokenized_text": [
                "Alice", "loves", "programming", "in", "Python", ".", "She", "also", "uses", "Lua", "for", "game", "development", "."
            ],
            "ner": [
                [0, 0, "Person"],
                [4, 4, "ProgrammingLanguage"],
                [10, 10, "ProgrammingLanguage"],
                [11, 12, "Activity"]
            ]
        },
        {
            "tokenized_text": [
                "Bob", "is", "a", "Java", "developer", "working", "at", "TechCorp", ".", "He", "enjoys", "machine", "learning", "."
            ],
            "ner": [
                [0, 0, "Person"],
                [3, 3, "ProgrammingLanguage"],
                [7, 7, "Organization"],
                [11, 12, "Field"]
            ]
        }
 ]
```

**Comment by urchade** [comment]
Hi @tomaarsen, I have trained 6 versions of GLiNER:

- Small, Medium, and Large versions trained on the Pile-NER dataset (https://huggingface.co/datasets/Universal-NER/Pile-NER-type). Pile-NER is licensed under "Attribution-NonCommercial 4.0 International."
- Small, Medium, and Large versions trained on the NuNer dataset (https://huggingface.co/datasets/numind/NuNER), which is licensed under MIT.

I want to upload them on the hub, but could not find how you converted the pre-trained weights into the HF format. Thanks!

Urchade

**Comment by tomaarsen** [comment]
Hello!

I used `model.save_pretrained("local_path")`

Or `model.push_to_hub("tomaarsen/blabla")`

- Tom Aarsen

**Comment by urchade** [comment]
Do you use any naming format at Hugging Face to differentiate between two versions of a model trained on different datasets?
