### ISSUE TITLE
Set user defined threshold for prediction in `custom_spacy_config`

### ISSUE THREAD

**Issue by shyamalaspure** [urchade/GLiNER#53]
I am using the defaut code as mentioned below:

```
import spacy
from gliner_spacy.pipeline import GlinerSpacy

# Configuration for GLiNER integration
custom_spacy_config = {
    "gliner_model": "urchade/gliner_multi",
    "chunk_size": 250,
    "labels": ["person", "organization", "email"],
    "style": "ent"
}

# Initialize a blank English spaCy pipeline and add GLiNER
nlp = spacy.blank("en")
nlp.add_pipe("gliner_spacy", config=custom_spacy_config)

# Example text for entity detection
text = "This is a text about Bill Gates and Microsoft."

# Process the text with the pipeline
doc = nlp(text)

# Output detected entities
for ent in doc.ents:
    print(ent.text, ent.label_)
```
Is there any way to define threshold in `custom_spacy_config` so as to get accurate prediction.
Also need to know  what is the default value of thershold.

**Comment by wjbmattingly** [comment]
I'm making that correction right now. Should be available shortly. Someone else has requested this an an issue. https://github.com/theirstory/gliner-spacy/issues/1

**Comment by wjbmattingly** [comment]
You can now use 

```bash
pip install gliner-spacy --upgrade
```

This will upgrade you to 0.0.3 which now allows you to set the threshold.

**Comment by wjbmattingly** [comment]
Yes, threshold will do it.

**Comment by shyamalaspure** [comment]
Thanks @wjbmattingly for prompt changes, it worked. Closing this thread.
