### ISSUE TITLE
Reproduction questions

### ISSUE THREAD

**Issue by yyDing1** [urchade/GLiNER#54]
Hi, I'm having some difficulty reproducing the OOD results.

I load the `gliner_large` model released [here](https://huggingface.co/urchade/gliner_large) and pass it to `get_for_all_path` for evaluation. However, my results are nearly 7% lower than the reported ones (60.9%) in the paper.

```
##############################################
step: 0
Table for zero-shot benchmark
CrossNER_AI         : 53.0%
CrossNER_literature : 57.7%
CrossNER_music      : 64.6%
CrossNER_politics   : 56.2%
CrossNER_science    : 58.0%
mit-movie           : 54.9%
mit-restaurant      : 33.5%
Average             : 54.0%
##############################################
```

Could the issue be that the released checkpoint is not compatible with the current code framework? What am I missing? Do you have any ideas?

**Comment by urchade** [comment]
The original version used AllenNLP (with cause dependency issues), so I have to reimplement some layers.

Recently, I have found some way to convert back the weight. I can upload the best large model to HF is you need

**Comment by urchade** [comment]
I have uploaded the large weight from the paper on HF under ```gliner_large```. Can you test it and tell me if it gives the expected results ? @yyDing1 

<img width="1096" alt="image" src="https://github.com/urchade/GLiNER/assets/38214774/478f1153-db84-4454-bccf-312ee52442c3">

**Comment by yyDing1** [comment]
It seems there are still some errors, and after updating the model, the results are as follows:

```
##############################################
step: 0
Table for zero-shot benchmark
CrossNER_AI         : 50.4%
CrossNER_literature : 46.3%
CrossNER_music      : 48.8%
CrossNER_politics   : 47.3%
CrossNER_science    : 46.1%
mit-movie           : 48.9%
mit-restaurant      : 36.2%
Average             : 46.3%
##############################################
```

**Comment by urchade** [comment]
The problem come from the forward pass of LSTM in AllenNLP, which is a bit different of mine

**Comment by urchade** [comment]
here is the code:

[Archive.zip](https://github.com/urchade/GLiNER/files/14908004/Archive.zip)

**Comment by yyDing1** [comment]
Thanks for your quick response and help; I have finally managed to reproduce the results reported in the paper.

```
##############################################
step: 0
Table for zero-shot benchmark
CrossNER_AI         : 57.2%
CrossNER_literature : 64.4%
CrossNER_music      : 69.6%
CrossNER_politics   : 72.6%
CrossNER_science    : 62.6%
mit-movie           : 57.2%
mit-restaurant      : 42.8%
Average             : 60.9%
##############################################
```

**Comment by urchade** [comment]
Hi @yyDing1, I am curious how you did it. Because, the performance of the models in HF seems lower. Did you use the original script in Archive.zip ?

**Comment by yyDing1** [comment]
I use the checkpoint released [here](https://drive.usercontent.google.com/download?id=1xEVyHZ1eOByA84RygkKcDt4UqAkoQ1D5&export=download&authuser=0). I found the checkpoint in the historical commits of your GitHub repository that I had followed before :)

**Comment by yyDing1** [comment]
Hi, there still exists some issues, the results of HF version are as follows:

```
##############################################
step: 0
Table for all datasets except crossNER
Table for zero-shot benchmark
CrossNER_AI         : 50.8%
CrossNER_literature : 46.2%
CrossNER_music      : 50.0%
CrossNER_politics   : 47.6%
CrossNER_science    : 46.8%
mit-movie           : 51.0%
mit-restaurant      : 35.2%
Average             : 46.8%
##############################################
```

I tried to debug and found some differences between the HF version and allennlp version.

The significant difference first appears in the output of flair embedding (or deberta model). (My HF flair version is 0.13.1)

I noticed some differences after tokenization and am uncertain about their potential impact on the final results.

Specifically, the input_ids in allennlp version:

```
tensor([[     1, 128001,   7416,  ...,      0,      0,      0],
        [     1, 128001,   7416,  ...,      0,      0,      0],
        [     1, 128001,   7416,  ...,      0,      0,      0],
        ...,
        [     1, 128001,   7416,  ...,    965,    323,      2],
        [     1, 128001,   7416,  ...,      0,      0,      0],
        [     1, 128001,   7416,  ...,      0,      0,      0]],
       device='cuda:0')
```

and the input_ids in HF version:
```
tensor([[     1, 128002,   7416,  ...,      0,      0,      0],
        [     1, 128002,   7416,  ...,      0,      0,      0],
        [     1, 128002,   7416,  ...,      0,      0,      0],
        ...,
        [     1, 128002,   7416,  ...,    965,    323,      2],
        [     1, 128002,   7416,  ...,      0,      0,      0],
        [     1, 128002,   7416,  ...,      0,      0,      0]],
       device='cuda:0')
```

**Comment by urchade** [comment]
Ok, maybe it is better to upload a completely new weight using the new version 🥺

**Comment by Shai-Meital** [comment]
Where can I find the datasets to send to the 'get_for_all_path' function? I can't find a minimal script for evolution

**Comment by Shai-Meital** [comment]
Can you guys share a minimal script for reproduction? I have found the datasets used but I can't seem to get the `get_for_all_path` to run.  The dataset file is called IE_INSTRUCTIONS.zip

**Comment by th0rntwig** [comment]
Where can I find the benchmark datasets in the correct format to run `get_for_all_path`?

**Comment by urchade** [comment]
Hi @th0rntwig, you can download the dataset here:: "https://drive.google.com/file/d/1T-5IbocGka35I7X3CE6yKe5N_Xg2lVKT/view"

**Comment by th0rntwig** [comment]
Thank you :)

**Comment by robcaulk** [comment]
> Ok, maybe it is better to upload a completely new weight using the new version 🥺

Hey @urchade did you update weights on HF for medium and large? We are unable to reproduce the published table.

For example: the published results say gliner medium gets 59.7 on literature in Table 1. Our attempts can only get 53 on literature for the hugging face published gliner medium. Generally this is the difference in performance that is observed across all datasets when we attempt to reproduce the benchmarks.

**Comment by urchade** [comment]
Hi @robcaulk, the result for GLiNER-M should be around 55-56 on OOD benchmark.

Unfortunately, the weights of the model published in the paper are not compatible with the current version, as it uses AllenNLP and an earlier version of PyTorch (see code here: https://github.com/urchade/GLiNER/issues/54#issuecomment-2043118319). I tried to convert the weights but it results in other bugs causing high drops in performance (see higher in this thread). The models on HF are the reproduction using the current codebase.

<img width="620" alt="image" src="https://github.com/urchade/GLiNER/assets/38214774/a34932a6-97e6-46e9-9b9e-427e59d395e8">

**Comment by urchade** [comment]
could you please provide me more information about your versions ? (hyperparameters, training data, ...) @robcaulk

**Comment by robcaulk** [comment]
@urchade for the CrossNER dataset, we are using the latest huggingface medium model:

https://huggingface.co/urchade/gliner_medium-v1

With the latest GLiNER github sources. We are using the evaluation you posted in this repo, so the hyperparameters remain unchanged https://github.com/urchade/GLiNER/blob/main/gliner/modules/run_evaluation.py#L92

We are using the evaluation following this approach: https://github.com/urchade/GLiNER/issues/54#issuecomment-2059161074

And using the data you posted here: https://github.com/urchade/GLiNER/issues/54#issuecomment-2066742863

Here we (with @thorntwig) compare Huggingface version to the results reported in the paper

![image](https://github.com/urchade/GLiNER/assets/20807672/180391a6-5d38-45c2-9f74-012738c49e41)

**Comment by urchade** [comment]
Oh, I see. Thank you for the evaluations!
The models in HF are not the same as the ones reported in the paper but a reproduction, due to the problem I mentioned earlier.
But from the table, it seems like the Medium version has quite bad performance for its size. I will investigate that and will upload a better model soon. For the large and small versions, the difference in results is not significant enough so I will keep them as they are.
As the earlier version of GLiNER is too difficult to use, I will update the table in the paper with the latest results (HF version).

**Comment by urchade** [comment]
I just trained a medium-sized GLiNER and got **54.6** in average:

- **CrossNER_science**: F1 = 55.91
- **mit-restaurant**: F1 = 34.41
- **CrossNER_AI**: F1 = 51.88
- **CrossNER_politics**: F1 = 67.35
- **mit-movie**: F1 = 46.85
- **CrossNER_music**: F1 = 66.46
- **CrossNER_literature**: F1 = 59.51

It is now on HF @robcaulk

**Comment by robcaulk** [comment]
Thanks, we will use this as the comparison!
