### ISSUE TITLE
Load the base model offfline

### ISSUE THREAD

**Issue by msamwelmollel** [urchade/GLiNER#6]
I downloaded the model from HF and stored it offline. However, I can't access the model offline; whenever I specify the model path it starts to download from the HF.

from model import GLiNER
path = "./gliner_base"

model = GLiNER.from_pretrained(path )
![image](https://github.com/urchade/GLiNER/assets/47386502/c21e4bf8-bc88-4961-a190-9626ebb05cc4)

**Comment by urchade** [comment]
Hi, you can do it like this

```python
from model import GLiNER

model = GLiNER.from_pretrained("urchade/gliner_base")
# or
model = GLiNER.from_pretrained("urchade/gliner_multi")

# or with local files:

model = GLiNER.from_pretrained("local_gliner_base")
# or
model = GLiNER.from_pretrained("local_gliner_multi")
# where `local_gliner_base` and `local_gliner_multi` are local directories with `gliner_base.pt` and `gliner_multi.pt` in them, respectively
```

**Comment by msamwelmollel** [comment]
Thank you for your prompt response. I tried to change. 

model = GLiNER.from_pretrained("gliner_base", local_files_only=True)

It works as a charm; be blessed.
