### ISSUE TITLE
[Urgent] Oh no. Error running app in Streamlit

### ISSUE THREAD

**Issue by huseyincenik** [urchade/GLiNER#61]
I developed a streamlit ner application with the gliner from Hugging Face. Even though the application runs locally, streamlit gives an error "Oh no.

Error running app. “If this keeps happening, please contact support.” What should I do about this? Where am I making a mistake?

My code blocks: [streamlit_ner_with_gliner/app.py at main · huseyincenik/streamlit_ner_with_gliner · GitHub](https://github.com/huseyincenik/streamlit_ner_with_gliner/blob/main/app.py)

My Streamlit App: https://ner-with-gliner.streamlit.app/

![image](https://github.com/urchade/GLiNER/assets/127469334/f2d7ac61-07f7-4c6d-917a-d6c59e09bb9e)
![image](https://github.com/urchade/GLiNER/assets/127469334/45ce3597-d536-4ead-a3f4-f74a5934d3eb)

**Comment by urchade** [comment]
Hi @huseyincenik 

is it possible to have more detailled error message ? I am not familiar with streamlit

**Comment by huseyincenik** [comment]
> Hi @huseyincenik
> 
> is it possible to have more detailled error message ? I am not familiar with streamlit

Hello, of course the error is as follows: "❗️ The service has encountered an error while checking the health of the Streamlit app: Get "http://localhost:8501/script-health-check": EOF"
I'm also adding log records.

[logs-huseyincenik-streamlit_ner_with_gliner-main-app.py-2024-04-11T07_30_10.480Z.txt](https://github.com/urchade/GLiNER/files/14942824/logs-huseyincenik-streamlit_ner_with_gliner-main-app.py-2024-04-11T07_30_10.480Z.txt)

**Comment by tomaarsen** [comment]
I can't find anything in the logs or provided information that indicates that something broke on the GLiNER side:

```
[06:37:33] ❗️ The service has encountered an error while checking the health of the Streamlit app: Get "http://localhost:8501/script-health-check": EOF
[06:39:06] ❗️ Streamlit server consistently failed status checks
[06:39:06] ❗️ Please fix the errors, push an update to the git repo, or reboot the app.
```

- Tom Aarsen

**Comment by huseyincenik** [comment]
@tomaarsen @urchade Thanks. The problem was caused by streamlit. It was fixed after making changes. Would you like to try the Streamlit app?

🚀 Thrilled to introduce our new NER (Named Entity Recognition) application powered by Gliner! 🛠️ Easily extract entities from your data with just a few clicks using GLiNER models. Choose from a variety of models like Gliner Multi-v2.1, Gliner Medium-v2.1, Gliner Small-v2.1, and Gliner Large-v2.1. Upload your dataset, define new columns with NER labels (separated by commas for multiple labels in one column), set thresholds for precision, process the data, and download the results as an Excel file! Try it out now!

🔗 App: https://lnkd.in/dGRBwRyF ✨
🔗 Github: https://lnkd.in/d3EQhKUx ✨
