### ISSUE TITLE
What is the maximum size of text input to be processed by the model ?

### ISSUE THREAD

**Issue by GabrielShenouda** [urchade/GLiNER#76]
Hi, like said in the title, i was wondering what was the limit in terms of caracters (or tokens ?).
Because i never had any warning while putting big portion of texts, but i can see that not everything is taken into account...

Thanks !

**Comment by urchade** [comment]
It is limited to 384 words (around 512 subtokens)

**Comment by urchade** [comment]
You have to chunk your text, as the pretrained model I used (deberta) has limited context length

**Comment by GabrielShenouda** [comment]
Ok thanks ! 
It would be great if it had a warning instead of just troncating the text while saying nothing if you want to improve the function ! 

Have a great day

**Comment by urchade** [comment]
Thanks for the suggestion. I have added a warning in the newer version!

**Comment by adantart** [comment]
> It is limited to 384 words (around 512 subtokens)

is it possible to fine-time 

> deberta

I'd like to help if possible to pretrain with a model with higher limit ... is it possible ?
also, I'd like to public one specific for legal sector, tell me how to do it (i have all datasets necessary) and I can publish it !
