### ISSUE TITLE
SpanMarkerNER compatibility

### ISSUE THREAD

**Issue by isaacrodrgz** [urchade/GLiNER#77]
Hi, just wanted to ask if there's any plan to making GLiNER models compatible with @tomaarsen https://github.com/tomaarsen/SpanMarkerNER package to make fientuning easier since that package already provides several functionalities for NER tasks. Thanks!

**Comment by tomaarsen** [comment]
Hello!

I'm afraid that an integration will not be elementary. That said, an integration with the `transformers` Trainer, like I've done for SpanMarker, should be possible. It will unlock some nice behaviour like a ton of training options, weights and biases & tensorboard integrations, etc.
It will however require some work. I'm afraid I don't have the kind of time to work on it.

- Tom Aarsen

**Comment by isaacrodrgz** [comment]
Thanks @tomaarsen! Yeah, making it at least compatible with the `transformers` ecosystem would be very nice.
