### ISSUE TITLE
'batch_predict_entities' having persisting CUDA memory, causing overflows.

### ISSUE THREAD

**Issue by qu-gg** [urchade/GLiNER#78]
Hi there! Thanks a ton for the model and work, great stuff and approachable to work with.
I ran into an issue when running the _batch_predict_entities_ function in a loop on GPU.

It seems like some objects are persisting on the GPU inbetween calls, causing a memory overflow a few iterations in. The idle model loaded in is 2GB mem, after passing in a batch of tokens sized [28, 380], it ends (and persists) with 8GB mem. Then on the next two calls, it goes to 14GB and OOM respectively.

I haven't been able to find what exactly to clear between runs - whether that is some model state or detaching the outputs.
Any advice on this would be appreciated!

**Comment by urchade** [comment]
Hum, I do not really know

can you try `torch.cuda.empty_cache()` after each iteration ?

**Comment by qu-gg** [comment]
Nice! Seems to have done the trick. 

Thanks for the quick reply and help; had looked at some ray.remote approaches and wanted to avoid that.
