### ISSUE TITLE
Create finetuning script/notebook

### ISSUE THREAD

**Issue by urchade** [urchade/GLiNER#8]

**Comment by drewskidang** [comment]
Waiting patiently but if you had example of data format that would be great

**Comment by urchade** [comment]
Hi, the data is a json containing a list of dictionnaries

```
[
        {
            "tokenized_text": [
                "Alice", "loves", "programming", "in", "Python", ".", "She", "also", "uses", "Lua", "for", "game", "development", "."
            ],
            "ner": [
                [0, 0, "Person"],
                [4, 4, "ProgrammingLanguage"],
                [10, 10, "ProgrammingLanguage"],
                [11, 12, "Activity"]
            ]
        },
        {
            "tokenized_text": [
                "Bob", "is", "a", "Java", "developer", "working", "at", "TechCorp", ".", "He", "enjoys", "machine", "learning", "."
            ],
            "ner": [
                [0, 0, "Person"],
                [3, 3, "ProgrammingLanguage"],
                [7, 7, "Organization"],
                [11, 12, "Field"]
            ]
        }
 ]
```

**Comment by drewskidang** [comment]
Thank you!! I saw your ATG repo as well. Did you have plans to ramp that as well

**Comment by urchade** [comment]
@drewskidang Thanks for your interest on ATG. I can work on releasing a pretrained weight, but I am not sure if it would be useful as public datasets for entity and relation extraction are poor and small-scale.

The good news is that ATG can be extended similarly as GLiNER, by conditioning the graph generation by the entity and/or relations types (both ATG and GLiNER use span-based representation). But,  it requires building an IE dataset with diverse entity and relation types.

**Comment by deepanshu2207** [comment]
Thank for opening this issue.

**Comment by urchade** [comment]
preprocessing for pile-ner/nuner available at https://github.com/urchade/GLiNER/tree/main/data

**Comment by drewskidang** [comment]
@urchade  thank you!!! Also is that data you used to pretrain it?

**Comment by urchade** [comment]
Hi @drewskidang, the results from the paper (https://arxiv.org/pdf/2311.08526.pdf) are from pre-training with Pile-NER. Results for NuNer are also available on huggingface (https://huggingface.co/urchade). Pile-NER yield stronger results as its texts are longer

I will try to work on ATG the coming days

**Comment by urchade** [comment]
Finetuning (minimal) notebook is available: https://github.com/urchade/GLiNER/blob/main/examples/finetune.ipynb

**Comment by deepanshu2207** [comment]
Thank you!
