### ISSUE TITLE
Long context support

### ISSUE THREAD

**Issue by xingchaozh** [urchade/GLiNER#95]
Hey @urchade Is there a plan for longer context support? I checked the config.yaml, the max allowed length is 384, this limits the usage for inference on larger document. Thank you in advance!

**Comment by urchade** [comment]
Hi @xingchaozh 
You can check this version which support up to 4k tokens: https://huggingface.co/numind/NuNER_Zero-4k

(Though the performance is lower as it uses long former)

**Comment by xingchaozh** [comment]
@urchade Thank you! I also found this version and raised one small issue there regarding the training example since it's out of date.

**Comment by urchade** [comment]
hi @xingchaozh, I should create a function for that soon

**Comment by hiral-t** [comment]
@urchade Have you created any function to handle large size context? I am also facing same issue like not able to handle large context.

**Comment by urchade** [comment]
Sorry, I forget to respond @hiral-t @xingchaozh . You can do long context prediction using the function `predict_long_text`. For now it only support  for batch_size=1.

```python
from typing import List, Dict, Any

def split_text_into_chunks(text: str, chunk_size: int) -> List[str]:
    words = text.split()
    return [' '.join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size)]

def calculate_offsets(chunks: List[str]) -> List[int]:
    offset = 0
    offsets = []
    for chunk in chunks:
        offsets.append(offset)
        offset += len(chunk) + 1  # +1 for the space that was removed during split
    return offsets

def adjust_indices(entities: List[Dict], offset: int) -> List[Dict]:
    for entity in entities:
        entity["start"] += offset
        entity["end"] += offset
    return entities

def predict_long_text(model, text: str, labels: List[str], chunk_size: int = 384) -> List[Dict]:
    if chunk_size <= 0:
        raise ValueError("chunk_size must be greater than 0")

    chunks = split_text_into_chunks(text, chunk_size)
    offsets = calculate_offsets(chunks)

    all_entities = []
    chunk_entities_list = model.batch_predict_entities(chunks, labels, threshold=0.5)

    for chunk_entities, offset in zip(chunk_entities_list, offsets):
        adjusted_entities = adjust_indices(chunk_entities, offset)
        all_entities.extend(adjusted_entities)

    return all_entities

**Comment by Opperessor** [comment]
just a doubt if the sentence is split in words of length 384, would'nt the context of the setence be effected, resulting in low accuracy?
