### ISSUE TITLE
Option to add prompt context to each label

### ISSUE THREAD

**Issue by koaning** [urchade/GLiNER#97]
This might be a 'future work'-thing. But might it be possible to have a version where I am able to add a sentence or two to each label? Something that allows me to explain what the label is supposed to mean? In all of my other prompting work I have noticed that this can really make a huge difference.

**Comment by urchade** [comment]
hi @koaning, a model for that should be released soon.

**Comment by urchade** [comment]
Hi @koaning, a new gliner version has been recently released. It should understand more detailled instruction. There is a demo on hugging face by @Ingvarstep : https://huggingface.co/spaces/knowledgator/GLiNER_HandyLab

**Comment by urchade** [comment]
you can load the model using the gliner library: `knowledgator/gliner-multitask-large-v0.5`
